# Configuration settings
data:
  raw_csv_path: D:/IIT BBS/Job Resources/Riverline\Riverline_NBA_system/data/raw/twcs.csv
  sqlite_db_path: D:/IIT BBS/Job Resources/Riverline\Riverline_NBA_system/data/processed/tweets.db
  new_raw_csv_path: D:/IIT BBS/Job Resources/Riverline/Riverline_NBA_system/data/raw/new_tweets.csv

sqlite:
  raw_table: raw_tweets
  interaction_table: interaction_table
  user_behaviour_tags_table: user_behaviour_tags
  new_raw_table: new_raw_tweets
  new_interaction_table: new_interaction_table

output:
  parsed_conversations_path: D:/IIT BBS/Job Resources/Riverline/Riverline_NBA_system/outputs/json/new_parsed_conversations.json
  tagged_conversations_path: D:/IIT BBS/Job Resources/Riverline/Riverline_NBA_system/outputs/json/new_tagged_conversations.json
  resolved_chat_log_csv: D:/IIT BBS/Job Resources/Riverline/Riverline_NBA_system/outputs/csv/nba_actions_log.csv
  flow_clusters_csv: "D:/IIT BBS/Job Resources/Riverline/Riverline_NBA_system/outputs/csv/conversation_flow_clusters.csv"
